"use client"

import { Button } from "@/components/ui/button"
import { Share2, Download, Check } from "lucide-react"
import { useState } from "react"
import { useToast } from "@/hooks/use-toast"
import type { Event } from "@/types/events"

interface EventActionsProps {
    event: Event
}

export function EventActions({ event }: EventActionsProps) {
    const { toast } = useToast()
    const [copied, setCopied] = useState(false)

    const handleShare = async () => {
        const shareData = {
            title: event.title,
            text: `Check out this event: ${event.title}`,
            url: window.location.href,
        }

        try {
            if (navigator.share) {
                await navigator.share(shareData)
            } else {
                await navigator.clipboard.writeText(window.location.href)
                setCopied(true)
                toast({
                    title: "Link copied!",
                    description: "Event link has been copied to your clipboard.",
                })
                setTimeout(() => setCopied(false), 2000)
            }
        } catch (err) {
            console.error("Error sharing:", err)
        }
    }

    const handleDownload = () => {
        // Generate a simple text file with event details
        const content = `
EVENT DETAILS: ${event.title}
----------------------------------
Date: ${new Date(event.date).toLocaleDateString("en-US", {
            weekday: "long",
            year: "numeric",
            month: "long",
            day: "numeric",
        })}
Time: ${event.time || "TBD"}
Location: ${event.location || "TBD"}
Category: ${event.category || "General"}

DESCRIPTION:
${event.description?.replace(/<[^>]*>/g, "") || "No description provided."}

Link: ${window.location.href}
----------------------------------
Generated by Acumen Haven
    `.trim()

        const blob = new Blob([content], { type: "text/plain" })
        const url = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = `${event.title.replace(/\s+/g, "_")}_details.txt`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)

        toast({
            title: "Details downloaded!",
            description: "Event information has been saved to your device.",
        })
    }

    return (
        <div className="space-y-3">
            <Button
                variant="outline"
                className="w-full bg-transparent border-slate-200 hover:bg-slate-50 hover:border-emerald-500 hover:text-emerald-600 transition-all duration-300"
                onClick={handleShare}
            >
                {copied ? (
                    <Check className="mr-2 h-4 w-4 text-emerald-600" />
                ) : (
                    <Share2 className="mr-2 h-4 w-4" />
                )}
                {copied ? "Copied!" : "Share Event"}
            </Button>

            <Button
                variant="outline"
                className="w-full bg-transparent border-slate-200 hover:bg-slate-50 hover:border-emerald-500 hover:text-emerald-600 transition-all duration-300"
                onClick={handleDownload}
            >
                <Download className="mr-2 h-4 w-4" />
                Download Details
            </Button>
        </div>
    )
}
